#+TITLE: Software Engineering Lab Assignment 1
#+SUBTITLE: Seshal Jain, Scholar Number 191112436, CSE 3
#+OPTIONS: h:2 num:nil toc:nil author:nil
#+DATE: [2021-01-22 Fri]
#+LATEX_HEADER: \usepackage[margin=0.7in]{geometry}
#+EXPORT_FILE_NAME: 191112436

* Introduction
Three Word URL generates short and easy to read URLs to share on the go, with the option to choose the lifetime of the URL while generating it.
* Description/Overview
The software provides a platform for the user to generate URLs for sharing. The generated URLs are in the form of website routes made from 3 easy to remember English words, which redirect the user to the original website. The words used can be shared verbally, and thus are easier to remember. The project has the added advantage of having an easy way to shorten complicated URLs temporarily, this is extremely useful for teams for sharing resources at short notice.
* COMMENT Clients:
Individuals or Development teams working on projects who need to share URLs.
* Feasibility
** Technical Feasibility
Possible frameworks that can be used
1. Python based Django
2. Python based Flask
3. Node.js based ExpressJS
Based on the developer availability, our best option is to go with Python based Django.
** Operational Feasibility
After the deployment of the project on the server, no maintenance is required for the project.
There may be some downtime when the server on which the project is running goes down.
** Economic Feasibility
The major costs associated with this project after development are the hosting and maintenance costs.
The capital required for covering costs of hosting may be generated from showing non-intrusive advertisements on the redirection page.
* Requirements
** Functional Requirements
1. The ability to generate short urls that are easy to read.
2. Proper redirection, with minimum to no downtime.
3. Fast response and redirection.
4. Ability to handle non-existing and invalid urls.
** Non Functional Requirements
1. Security - The data shouldn’t be easily breached and data shouldn’t be corrupted and url lifetime scope shouldn’t be able to be changed by unauthorized people.
2. Maintenance - The project itself doesn’t require management after the deployment, however the server may require regular maintenance.
* COMMENT Goals and Scopes
1. Users should be able to generate a 3-word-URL for the required links.
2. Users should have the option to choose the validity duration for the generated URL.
3. Users must be able to generate URLs for even non existent websites.
* COMMENT Developer Responsibility
The developer team will take the responsibility of the project.
* COMMENT Platform
1. Website
2. Progressive Web App for installation on phone
* COMMENT Deliverables
The development team will deliver the following after the course of development:
1. Feature Specification
2. Test Plan for the project
3. Product design and structure
4. A thorough report of the project
5. Source Code
* Risk Management: (Identification and Mitigation)
1. In case of database failure, the URLs and routes may be lost.
2. This can be resolved via timed backups and regular DBMS checkups.
